# isort
[tool.isort]
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 88
lines_after_imports = 2
force_single_line = true
force_sort_within_sections = true
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,TESTS,LOCALFOLDER"
known_tests = ["tests"]
skip = [
    "docs/conf.py",
]


# pylint
# TOML support in pylint has shortcomings:
# - numeric values must be expressed as strings (e.g. max-line-length)
# - TOML lists are not supported, strings should be used (with comma-separated values)
# See  https://github.com/PyCQA/pylint/issues/3538 for the latter (at least)
[tool.pylint.MASTER]
load-plugins = """,
pylint_strict_informational
"""

[tool.pylint.REPORTS]
msg-template = "{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}"

[tool.pylint.FORMAT]
max-line-length = "120"

[tool.pylint."MESSAGES CONTROL"]
enable = """,
use-symbolic-message-instead,
useless-suppression
"""

disable = """,
arguments-differ,
attribute-defined-outside-init,
bad-continuation,
cyclic-import,
duplicate-code,
fixme,
file-ignored,
import-outside-toplevel,
invalid-name,
locally-enabled,
locally-disabled,
missing-docstring,
no-init,
no-member,
no-self-use,
old-style-class,
protected-access,
redefined-variable-type,
superfluous-parens,
too-few-public-methods,
too-many-ancestors,
too-many-arguments,
too-many-branches,
too-many-instance-attributes,
too-many-lines,
too-many-locals,
too-many-public-methods,
too-many-statements,
ungrouped-imports,
unused-argument,
useless-return,
wrong-import-order
"""